def is_line_in_file(file_path, target_line):
    with open(file_path, 'r') as file:
        for line in file:
            if target_line in line:
                return True
    return False

file_path = "../data/DrugBank2021.csv"  # 替换为你要搜索的文件路径
target_line = "DB06148 P21918 CN1CCN2C(C1)C1=CC=CC=C1CC1=CC=CC=C21 MLPPGSNGTAYPGQFALYQQLAQGNAVGGSAGAPPLGPSQVVTACLLTLLIIWTLLGNVLVCAAIVRSRHLRANMTNVFIVSLAVSDLFVALLVMPWKAVAEVAGYWPFGAFCDVWVAFDIMCSTASILNLCVISVDRYWAISRPFRYKRKMTQRMALVMVGLAWTLSILISFIPVQLNWHRDQAASWGGLDLPNNLANWTPWEEDFWEPDVNAENCDSSLNRTYAISSSLISFYIPVAIMIVTYTRIYRIAQVQIRRISSLERAAEHAQSCRSSAACAPDTSLRASIKKETKVLKTLSVIMGVFVCCWLPFFILNCMVPFCSGHPEGPPAGFPCVSETTFDVFVWFGWANSSLNPVIYAFNADFQKVFAQLLGCSHFCSRTPVETVNISNELISYNQDIVFHKEIAAAYIHMMPNAVTPGNREVDNDEEEGPFDRMFQIYQTSPDGDPVAESVWELDCEGEISLDKITPFTPNGFH 1"  # 替换为你要查找的行

if is_line_in_file(file_path, target_line):
    print(f"The line '{target_line}' is in the file.")
else:
    print(f"The line '{target_line}' is not in the file.")
